# Generated by Django 5.2.8 on 2025-11-25 14:30

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to=store.models.get_file_path)),
                ('small_description', models.TextField(max_length=75)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=75)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0=default,1-Hidden')),
                ('trending', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=15)),
                ('meta_title', models.CharField(max_length=10)),
                ('meta_keyword', models.CharField(max_length=15)),
                ('meta_description', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
