# Generated by Django 5.2.8 on 2025-11-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keyword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_description',
            field=models.TextField(max_length=150),
        ),
    ]
