# Generated by Codex on 2026-03-12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_status_alter_product_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=False, default='Unknown', max_length=60, null=False),
        ),
    ]
